name: deployment
on: [push]
jobs:
  update-source:
    runs-on: ubuntu-latest
    steps:
      - uses: muinmomin/webhook-action@v1.0.0
        with:
          url: "https://k2.kebtke.id/deploy"
          data: "{'command': 'publish'}"