name: deployment
on: [push]
jobs:
  update-source:
    runs-on: ubuntu-latest
    steps:
      - uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ secrets.DEPLOY_URL }}
          data: "{'command': 'publish'}"